### ISSUE TITLE
[Bug] Conflicts with "Mod Menu" mod 

### ISSUE THREAD

**Issue by studiobutter** [KingContaria/FastQuit#43] opened 2024-03-09 18:19 UTC
I use a Mod call [Mod Menu](https://modrinth.com/mod/modmenu) that shows the Menu for the Mods I'm using. Somehow there's a conflict that cause it to crash.

**Comment by tildejustin** [comment] 2024-03-09 18:29
please consider attaching or linking to a crash log

**Comment by KingContaria** [comment] 2024-03-17 11:56
Hi,
I can't reproduce any crashes using [FastQuit 3.0.0 for 1.20.4](https://modrinth.com/mod/fastquit/version/3.0.0+1.20.4), [Mod Menu 9.0.0](https://modrinth.com/mod/modmenu/version/9.0.0) and [Cloth Config v13.0.121](https://modrinth.com/mod/cloth-config/version/13.0.121+fabric) on Fabricloader 0.15.7.
Could you send a log + crashreport so I can look into what causes the crash?

**Comment by studiobuttermedia** [comment] 2024-03-17 14:35
I guess this is the one
```log
[01:11:56] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.7
[01:11:57] [main/WARN]: Warnings were found!
 - Mod 'Sodium Extra' (sodium-extra) 0.5.4+mc1.20.4-build.116 recommends version 1.4.2 or later of reeses-sodium-options, which is missing!
	 - You should install version 1.4.2 or later of reeses-sodium-options for the optimal experience.
[01:11:57] [main/INFO]: Loading 88 mods:
	- cloth-config 13.0.121
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.96.4+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.14+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.3+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.3+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.1+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.25+58f8c0124f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.8+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.64+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.13+080016e44f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.19+58f8c0124f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.1+e761c6694f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.19+58f8c0124f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.11+e84342304f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- fastquit 3.0.0+1.20.4
	- indium 1.0.30+mc1.20.4
	- iris 1.6.17
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- languagereload 1.5.10+1.20.3
	- lazydfu 0.1.3
	- lithium 0.12.1
	- memoryleakfix 1.1.5
	- minecraft 1.20.4
	- modelfix 1.14
	- modmenu 9.0.0
	- noxesium 1.2.0+669ccb7
	   \-- com_noxcrew_noxesium_api_ 1.2.0+669ccb7
	- replaymod 1.20.4-2.6.14
	- sodium 0.5.8+mc1.20.4
	- sodium-extra 0.5.4+mc1.20.4-build.116
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
[01:11:57] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Launchers/MultiMC/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[01:11:57] [main/INFO]: Compatibility level set to JAVA_17
[01:11:58] [main/INFO]: Loaded configuration file for Lithium: 129 options available, 0 override(s) found
[01:11:58] [main/WARN]: Reference map 'memoryleakfix-fabric-1.17+-fabric-refmap.json' for memoryleakfix-fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[01:11:58] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
[01:11:58] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 3 override(s) found
[01:11:58] [main/INFO]: Loaded configuration file for Sodium Extra: 34 options available, 0 override(s) found
[01:11:59] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[01:11:59] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[01:11:59] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[01:11:59] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[01:11:59] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[01:11:59] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[01:11:59] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[01:11:59] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[01:11:59] [main/INFO]: [MemoryLeakFix] Will be applying 3 memory leak fixes!
[01:11:59] [main/INFO]: [MemoryLeakFix] Currently enabled memory leak fixes: [targetEntityLeak, biomeTemperatureLeak, hugeScreenshotLeak]
[01:12:00] [main/WARN]: Error loading class: net/optifine/render/ChunkVisibility (java.lang.ClassNotFoundException: net/optifine/render/ChunkVisibility)
[01:12:00] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[01:12:00] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[01:12:00] [main/INFO]: Searching for graphics cards...
[01:12:00] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[01:12:00] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=AMD, name=AMD Radeon(TM) Graphics, version=DriverVersion=31.0.12044.3]
[01:12:13] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[01:12:13] [Render thread/INFO]: Setting user: Studio_Butter
[01:12:14] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[01:12:14] [Render thread/ERROR]: Mod fastquit provides a broken implementation of ModMenuApi
java.lang.NoClassDefFoundError: Could not initialize class com.kingcontaria.fastquit.FastQuit
	at com.kingcontaria.fastquit.ModMenuIntegration.getModConfigScreenFactory(ModMenuIntegration.java:13) ~[fastquit-3.0.0+1.20.4.jar:?]
	at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$1(ModMenu.java:76) ~[modmenu-9.0.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.terraformersmc.modmenu.ModMenu.onInitializeClient(ModMenu.java:71) ~[modmenu-9.0.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) ~[fabric-loader-0.15.7.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:487) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1: 
```

**Comment by studiobuttermedia** [comment] 2024-03-17 14:37
Yeah it was the "Mod fastquit provides a broken implementation of ModMenuApi" line that cause with this issue

**Comment by KingContaria** [comment] 2024-03-17 15:07
I installed the mods from your log but couldnt reproduce any issues with this list:
- [FastQuit](https://modrinth.com/mod/fastquit/version/3.0.0+1.20.4)
- [Mod Menu](https://modrinth.com/mod/modmenu/version/9.0.0)
- [Cloth Config API](https://modrinth.com/mod/cloth-config/version/13.0.121+fabric)
- [Fabric API](https://modrinth.com/mod/fabric-api/version/0.96.4+1.20.4)
- [Fabric Language Kotlin](https://modrinth.com/mod/fabric-language-kotlin/version/1.10.19+kotlin.1.9.23)
- [Indium](https://modrinth.com/mod/indium/version/1.0.30+mc1.20.4)
- [Iris Shaders](https://modrinth.com/mod/iris/version/1.6.17+1.20.4)
- [Language Reload](https://modrinth.com/mod/language-reload/version/1.5.10+1.20.3)
- [LazyDFU](https://modrinth.com/mod/lazydfu/version/0.1.3)
- [Lithium](https://modrinth.com/mod/lithium/version/mc1.20.4-0.12.1)
- [MemoryLeakFix](https://modrinth.com/mod/memoryleakfix/version/3w0IxNtk)
- [Model Gap Fix](https://modrinth.com/mod/modelfix/version/1.14)
- [Noxesium](https://modrinth.com/mod/noxesium/version/1.2.0)
- [ReplayMod](https://modrinth.com/mod/replaymod/version/1.20.4-2.6.14)
- [Sodium](https://modrinth.com/mod/sodium/version/mc1.20.4-0.5.8)
- [Sodium Extra](https://modrinth.com/mod/sodium-extra/version/mc1.20.4-0.5.4)

Could you try reinstalling your mods, maybe one of the files got corrupted?
If that doesnt help, could you try reproducing the issue with just Mod Menu, FastQuit and Cloth Config API installed?

**Comment by KingContaria** [comment] 2024-05-02 13:38
Im going to close this issue now since I can't reproduce the issue, i will reopen it if any more info comes in

**Closed as completed by KingContaria** 2024-05-02 13:38 UTC
