### ISSUE TITLE
Quitting resets player head textures

### ISSUE THREAD

**Issue by Heir67** [KingContaria/FastQuit#42] opened 2023-12-14 01:32 UTC
Placing player heads will work fine normally, but after leaving a singleplayer world with fastquit installed, the texture will reset to Steve's head. This happened on every quit.

**Comment by KingContaria** [comment] 2024-01-08 01:51
Hey,
I followed [this tutorial](https://www.youtube.com/watch?v=fHbsq15RFB0) to get both player and custom heads and after quitting and rejoining the world, both worked completely fine.
Could you send a more detailed list of reproduction steps and a list of other mods that you are using?

**Comment by Heir67** [comment] 2024-01-08 05:40
Hi!
I've just tested again after reinstalling the mod and it looks like this
was a past issue that has already been fixed at some point, as it doesn't
happen anymore. I used the command from this website:
https://minecraft-heads.com/custom-heads/head/753-tv
and then simply left and when rejoining it was a steve head.

Originally the mod was installed in version 5.6.3 of this modpack:
https://www.curseforge.com/minecraft/modpacks/fabulously-optimized

I have added a couple mods to this modpack, Essential, and Axiom as well.
Thank you! :)

**Comment by KingContaria** [comment] 2024-01-08 10:26
Thanks for the response, I haven't actually updated the mod since this issue was created, so I'm assuming it was either another mods issue or an incompatibility with another mod that was resolved. Either way I'll close this ticket, thanks for the quick response :)

**Closed by KingContaria** 2024-01-08 10:26 UTC

**Comment by Heir67** [comment] 2024-01-08 17:53
All good! Thanks for looking into it for me :) have a good one! Cheers.
