### ISSUE TITLE
[CRASH] Incompatibility with Quilted Fabric API

### ISSUE THREAD

**Issue by TheCatRiX** [KingContaria/FastQuit#24] opened 2023-05-20 17:59 UTC
**Versions:**
- Minecraft 1.19.4
- Quilt Loader 0.18.10
- QFAPI 6.0.0-beta.6 and QSL 5.0.0-beta.5
- FastQuit 2.1.0

**Steps to reproduce:**
- Quit any world
- Start creating a new world before save toast appear
- Get a crash

Logs: https://mclo.gs/oILT6NM

**Comment by KingContaria** [comment] 2023-05-21 11:39
this seems to be caused by qsl saving some server related things in a static field instead of the server itself, which is fine in normal minecraft because theres only ever one server at the same time, but in this scenario with fastquit there is two.
there is no way for me to directly fix this unfortunately, i'll implement an option to not allow multiple servers tho that will automatically turn on when qsl is present
theoratically quilt could fix this but there is a good chance they wont (it might mess with the api)
you can make an issue and link this comment if you want tho

**Comment by KingContaria** [comment] 2023-06-22 15:03
i did not mean to close this yet since its just gonna be in the beta for now, didnt know github just does that as soon as you say youve fixed it in the commit message lol

**Closed** 2023-09-05 18:06 UTC
Labels: mod compatibility, fixed in upcoming release
