### ISSUE TITLE
C2ME strange incompatability

### ISSUE THREAD

**Issue by iMoobert** [KingContaria/FastQuit#37] opened 2023-09-16 18:34 UTC
Sorry, I hit enter before I realized this was supposed to go on c2me's issue page instead, and idk how to delete posts (If I figure it out this post will be deleted.)

Saving after quitting the world will always take over a minute to finish while c2me and fastquit is installed for some reason.

Removing c2me will solve the issue.

Edit: Marking as closed is as close to deleting as I can get, sorry.

**Comment by KingContaria** [comment] 2023-09-16 22:00
there's absolutely no harm in opening an issue on both pages, dont worry
since ive gotten a similar report thats also been closed im gonna look into this to see if maybe fastquit is causing a problem here

**Comment by KingContaria** [comment] 2023-09-16 22:09
could you maybe upload a minecraft log, i cant seem to reproduce the issue myself (there might be more mods causing this issue)

**Comment by iMoobert** [comment] 2023-09-17 00:55
Can do. I pasted c2me back into my mods folder, started up a new session, exited, forgot I put it back in, and thought "damn what's taking so long?" lol

Here's my **latest.log**; I assumed you meant this one but let me know if you wanted a different log

**Comment by KingContaria** [comment] 2023-09-17 01:05
Wait so what exactly was the chain of events here?
The way i understand it from the logs right now (might be wrong) it goes like this:

Join world -> Leave World -> Main Menu -> Press Quit Game -> it takes 59 seconds to save the world -> Minecraft finally closes

**Comment by iMoobert** [comment] 2023-09-17 05:02
Yes, that is exactly correct.

Open Minecraft -> Join World -> Leave World -> Press Quit Game - > Game takes 59 seconds to save the world -> Minecraft closes

That is exactly what happened for that log instance

**Comment by KingContaria** [comment] 2023-09-17 05:31
could you try how long saving takes with c2me but without fastquit?

**Comment by iMoobert** [comment] 2023-09-17 06:54
Sorry, yeah, didn't see your reply lol

Here's the [latest.log](https://mclo.gs/vrz62aR) with c2me and no fastquit

This time in a slightly different order because of no fastquit, but twice as long save time, which I guess means it for sure isn't because of FastQuit.

Start Minecraft -> Enter World -> Leave World -> Game takes 2mins 2s to save game -> Press Quit Game -> Minecraft closes

**Comment by KingContaria** [comment] 2023-09-17 09:21
yea okay, seems like a pure c2me issue then (or an issue with another mod you are using), i'll close this again then, thanks for your help! :)

**Closed by KingContaria** 2023-09-17 09:21 UTC
