### ISSUE TITLE
1.19.4 world disappearing till restart

### ISSUE THREAD

**Issue by Seth-the-cat** [KingContaria/FastQuit#23] opened 2023-05-14 10:22 UTC
I'm having a bug where as the title says the world disappears till restart.

Here is the [log line 4255 ](https://mclo.gs/tj9Di8C#L4255)seems to be the error.

**Comment by Seth-the-cat** [comment] 2023-05-14 10:32
here is a video demonstration: [link](https://bafybeibbdtrmoodi3os73ovbrx4dzyofe3vrw7ptatvgijgfkga76gpu3e.ipfs.dweb.link/)

**Comment by KingContaria** [comment] 2023-05-21 11:47
hey, this seems to be an incompatibility with one of your mods, could you try narrowing down which mod is causing troubles or send me a mod folder / modpack to download?

**Comment by Seth-the-cat** [comment] 2023-05-21 11:55
https://ipfs.io/ipfs/QmRg8C75RViHf8A1dBoMVTbSBsZDmdLzCxg1q8VYRYSPMA?filename=The%201.19.4%20Swag%20setup.zip

There's an ipfs zip file.

**Comment by KingContaria** [comment] 2023-05-21 12:05
it doesnt seem to be downloading for me unfortunately

**Comment by KingContaria** [comment] 2023-06-21 18:42
okay ive done some testing and this seems to be an incompatibility with geyser

**Comment by KingContaria** [comment] 2023-06-21 19:17
i was able to reproduce this with just geyser installed, no fastquit, so im gonna close this issue
please make an issue on their github if you are experiencing the issue on the latest geyser version

**Closed** 2023-06-21 19:17 UTC
Labels: invalid
