### ISSUE TITLE
crash on 1.19.3 when you click "singleplayer"

### ISSUE THREAD

**Issue by Mamsikas** [KingContaria/FastQuit#10] opened 2022-12-08 12:57 UTC

**Comment by KingContaria** [comment] 2022-12-08 18:38
fixed in [1.2.1-1.19.3](https://modrinth.com/mod/fastquit/version/1.2.1-1.19.3)

next time please provide a crashreport or other useful information in case i can't reproduce the issue, thanks! :)

**Closed by KingContaria** 2022-12-08 18:38 UTC
